ramangupta44/xmcloud-foundation-head

- src/items/EspireDemo.Layout/layout/Renderings/Project/Espire Components.yml
- src/items/EspireDemo.Layout/layout/Renderings/Project/Espire Components/Banner.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Home/Test Pages/HomePage Banner.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Home/Test Pages/HomePage Banner/Data/test.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Presentation/Headless Variants/Banner/Default.yml
- src/sxastarter/src/assets/sass/variants/banner/default.scss
- src/sxastarter/src/assets/sass/variants/banner/index.scss
- Added varaint
- Added styles for edit mode
- Renamed available rendering folder
- Added Thumbnail Image
> chore() : Banner Component Enhancement

- src/sxastarter/src/components/Espire/Listing/Listing.tsx
- src/sxastarter/src/lib/graphql/graphql-apollo-client.ts
- src/sxastarter/src/lib/middleware/smallcase-url.ts
- Added endpoint to fecth result from Delivery API endpoint
> Updated Apollo client graphql endpoint

- src/items/EspireDemo.Layout/layout/Renderings/Project/Espire Components/Social Media Feeds.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Presentation/Available Renderings/Espire.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Presentation/Headless Variants/Social Media Feeds.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Presentation/Headless Variants/Social Media Feeds/Default.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Component.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Feeds Folder.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Feeds Folder/__Standard Values.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Feeds.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Feeds/Details.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Feeds/Details/ClassName.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Feeds/Details/ID.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Feeds/Details/URL.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Feeds/__Standard Values.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Rendering Parameters.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Rendering Parameters/Social Media Feeds.yml
- src/items/EspireDemo.Template/templates/Feature/EspireDemo/Social Sharing/Rendering Parameters/Social Media Feeds/__Standard Values.yml
- src/sxastarter/src/components/Espire/SocialSharing/Feeds.tsx
- src/sxastarter/src/components/Espire/SocialSharing/SocialMediaFeeds.tsx
- src/sxastarter/src/lib/component-props/EspireTemplateProps/SocialMediaFeeds/SocialMediaFeedsProps.ts
- Added social media feed with SSR
> chore() : Added Social Media Feed component

- src/sxastarter/src/Layout.tsx
- src/sxastarter/src/components/Espire/Header/Cookie.tsx
- Added Civiv UK cookie
- Added Cookiebot - commented scripts
> Added cookie banner

- src/items/EspireDemo.Site/EspireDemo/Espire/Home/Components.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Home/Components/C1.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Home/Components/C2.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Home/Components/C3.yml
- src/items/EspireDemo.Site/EspireDemo/Espire/Presentation/Headless Variants/Listing/ListCard.yml
- src/items/EspireDemo.Template/templates/Project/EspireDemo/Component Details.yml
- src/items/EspireDemo.Template/templates/Project/EspireDemo/Component Details/Details.yml
- src/items/EspireDemo.Template/templates/Project/EspireDemo/Component Details/Details/Image.yml
- src/sxastarter/src/assets/sass/variants/listing/index.scss
- src/sxastarter/src/components/Espire/Listing/Listing.tsx
- src/sxastarter/src/lib/component-props/EspireTemplateProps/Listing/ListingProps.ts
- src/sxastarter/src/lib/graphql/query/listing.ts
- Added RV
- Added CSS file structure
- Created template
- Created and pushed test pages
> Listing Component - Added ListCard Variant

- src/sxastarter/next.config.js
- src/sxastarter/project-configs/header.js
- src/sxastarter/src/components/Espire/PageContent/PlainHTMLResuable.tsx
- Added Editable logic for PlainHTML Reusable
-  Added Headers
> Added Headers

- src/sxastarter/src/assets/sass/variants/article-banner/default.scss
- src/sxastarter/src/components/Espire/Header/Cookie.tsx
- src/sxastarter/src/components/Espire/PageContent/ArticleBanner.tsx
- Article banner issue
- Enable civic UK Cookie
> fix() : Component issues

- src/sxastarter/src/assets/basic/_fonts.scss
- src/sxastarter/src/assets/sass/base/fonts/_fonts.scss
- src/sxastarter/src/components/Espire/PageContent/Banner.tsx
Code and Css changes for improving lighthouse score
> Code and Css changes for improving lighthouse score

- src/sxastarter/.env
- src/sxastarter/next.config.js
- src/sxastarter/src/components/Espire/PageContent/Banner.tsx
Code Changes for Image Optimization
> Code Changes for Image Optimization

- src/sxastarter/.env
new domain added in Images Domain
> new domain added in Images Domain

- src/sxastarter/src/components/Espire/PageContent/Banner.tsx
> Code Change

- src/sxastarter/.env
- src/sxastarter/next.config.js
- src/sxastarter/src/components/Espire/PageContent/Banner.tsx
> Changes rollback

- src/platform/App_Data/Xdts/Web.config.xdt
handlers for Dianoga in webconfigxdt
> handlers for Dianoga in webconfigxdt

- src/platform/App_Data/Xdts/Web.config.xdt
> xdt commented for handlers

- src/sxastarter/.env
- src/sxastarter/next.config.js
- src/sxastarter/src/components/Espire/PageContent/Banner.tsx
> Code Changes

- src/sxastarter/.env
- src/sxastarter/next.config.js
> Config Changes

- src/sxastarter/.env
- src/sxastarter/next.config.js
- src/sxastarter/src/middleware.ts
middleware and next config changes for next image
> middleware and next config changes for next image

- src/sxastarter/.env
> personalization changes

- src/sxastarter/next.config.js
Next config js changes for domain whitelisted
> Next config js changes for domain whitelisted

- src/sxastarter/.env
- src/sxastarter/next.config.js
> Next config and env changes

- src/items/Espire Accelerator.Layout/layout/Renderings/Feature/Espire Accelerator/Espire Advance Components/Maps.yml
- src/items/Espire Accelerator.System/system/Settings/Feature/Espire Accelerator/Espire Advance Components/Espire Advance Components Headless Site Setup/Add Mapss Data Item.yml
- src/items/Espire Accelerator.System/system/Settings/Feature/Espire Accelerator/Espire Advance Components/Espire Advance Components Headless Site Setup/Rendering Variants/Maps.yml
- src/items/Espire Accelerator.Template/templates/Branches/Feature/Espire Accelerator/Espire Advance Components/Available Headless Espire Advance Components Renderings/#name.yml
- src/items/Espire Accelerator.Template/templates/Branches/Feature/Espire Accelerator/Espire Advance Components/Default Maps Variant.yml
- src/items/Espire Accelerator.Template/templates/Branches/Feature/Espire Accelerator/Espire Advance Components/Default Maps Variant/#name.yml
- src/items/Espire Accelerator.Template/templates/Branches/Feature/Espire Accelerator/Espire Advance Components/Default Maps Variant/#name/Default.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/Maps Folder.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/Maps Folder/__Standard Values.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/Maps.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/Maps/Maps.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/Maps/Maps/Address.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/Rendering Parameters/Maps.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/Rendering Parameters/Maps/__Standard Values.yml
- src/sxastarter/.env
- src/sxastarter/package-lock.json
- src/sxastarter/package.json
- src/sxastarter/src/components/Espire/Maps/Maps.tsx
- src/sxastarter/src/lib/component-props/EspireTemplateProps/Maps/MapsProps.ts
> code and yml changes

- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/MapLocation.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/MapLocation/Maps.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/MapLocation/Maps/Address.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/MapLocation/__Standard Values.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/Maps/Maps/AddressCollection.yml
- src/items/Espire Accelerator.Template/templates/Feature/Espire Accelerator/Espire Advance Components/Maps/__Standard Values.yml
- src/sxastarter/src/components/Espire/Maps/Maps.tsx
- src/sxastarter/src/lib/component-props/EspireTemplateProps/Maps/MapsProps.ts
Code and yml changes for Map component
> Code and yml changes for Map component

- headapps/nextjs-starter/src/Layout.tsx
canonical url link asnewpath changes
> canonical url link asnewpath changes

- headapps/nextjs-starter/src/assets/basic/_header.scss
- headapps/nextjs-starter/src/assets/sass/variants/index.scss
- headapps/nextjs-starter/src/assets/sass/variants/searchbar/default.scss
- headapps/nextjs-starter/src/assets/sass/variants/searchbar/index.scss
- headapps/nextjs-starter/src/components/Espire/Header/SearchBox.tsx
- headapps/nextjs-starter/src/sitecore-search/widgets/PreviewSearchList/index.tsx
- headapps/nextjs-starter/src/sitecore-search/widgets/PreviewSearchList/styles.module.css
- headapps/nextjs-starter/src/sitecore-search/widgets/SearchResultList/styles.module.css
- headapps/nextjs-starter/src/sitecore-search/widgets/components/ArticleHorizontalCard/styles.module.css
- headapps/nextjs-starter/src/sitecore-search/widgets/components/ResultsPerPage/styles.module.css
- headapps/nextjs-starter/src/sitecore-search/widgets/components/SearchFacets/styles.module.css
- headapps/nextjs-starter/src/sitecore-search/widgets/components/SearchPagination/styles.module.css
- headapps/nextjs-starter/src/sitecore-search/widgets/components/SuggestionBlock/styles.module.css
> css changes for search

- authoring/items/items/Espire Accelerator.Layout/layout/Renderings/Feature/Espire Accelerator/Espire Advance Components/Demo.yml
- authoring/items/items/Espire Accelerator.Layout/layout/Renderings/Feature/Espire Accelerator/Espire Advance Components/SearchResultListing.yml
- headapps/nextjs-starter/src/components/Espire/Header/Demo.tsx
- headapps/nextjs-starter/src/components/Espire/Header/Demo1.tsx
- headapps/nextjs-starter/src/components/Espire/SearchResult/SearchResultListing.tsx
debugging the searchresultlist
> debugging the searchresultlist

- headapps/nextjs-starter/src/assets/images/down-arrow.svg
- headapps/nextjs-starter/src/assets/images/right-arrow.svg
- headapps/nextjs-starter/src/sitecore-search/widgets/components/ResultsPerPage/styles.module.css
- headapps/nextjs-starter/src/sitecore-search/widgets/components/SearchFacets/styles.module.css
Added new UI changes for filter
> Added new UI changes for filter
